# Generated by Django 6.0.1 on 2026-01-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["portfolio_slug"], name="authenticat_portfol_388ebf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["github_username"], name="authenticat_github__60083f_idx"
            ),
        ),
    ]
