# Generated by Django 6.0.1 on 2026-01-29 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("portfolios", "0003_alter_portfoliosettings_min_stars_to_show"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("key", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["key"], name="themes_them_key_02515e_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="ThemeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "secondary_color",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "background_color",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                ("accent_color", models.CharField(blank=True, max_length=7, null=True)),
                ("text_color", models.CharField(blank=True, max_length=7, null=True)),
                (
                    "font_family",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("spacing", models.CharField(blank=True, max_length=20, null=True)),
                ("dark_mode_enabled", models.BooleanField(default=False)),
                ("border_radius", models.PositiveBigIntegerField(default=12)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "settings",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_config",
                        to="portfolios.portfoliosettings",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="themes.theme",
                    ),
                ),
            ],
        ),
    ]
