# Generated by Django 6.0.1 on 2026-02-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("themes", "0003_theme_created_by_theme_is_custom"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="default_config",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="themeconfig",
            name="spacing",
            field=models.CharField(
                blank=True,
                choices=[("sm", "Small"), ("md", "Medium"), ("lg", "Large")],
                max_length=10,
                null=True,
            ),
        ),
    ]
