# Generated by Django 6.0.1 on 2026-02-03 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("themes", "0004_theme_default_config_alter_themeconfig_spacing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="themeconfig",
            name="border_radius",
            field=models.PositiveBigIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
