# Generated by Django 5.2.4 on 2026-01-17 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GithubProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_username", models.CharField(max_length=255, unique=True)),
                ("github_id", models.BigIntegerField(unique=True)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("avatar_url", models.URLField(blank=True)),
                ("profile_url", models.URLField(blank=True)),
                ("public_repos", models.IntegerField(default=0)),
                ("followers", models.IntegerField(default=0)),
                ("following", models.IntegerField(default=0)),
                ("joined_date", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("blog", models.URLField(blank=True, null=True)),
                ("auto_sync", models.BooleanField(default=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                (
                    "sync_frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("manual", "Manual Only"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("show_forked_repos", models.BooleanField(default=False)),
                ("excluded_repos", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Profile",
                "verbose_name_plural": "GitHub Profiles",
            },
        ),
        migrations.CreateModel(
            name="GitHubSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sync_type", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        max_length=20,
                    ),
                ),
                ("repos_synced", models.IntegerField(default=0)),
                ("commits_synced", models.IntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "github_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="github_integration.githubprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("github_id", models.BigIntegerField(unique=True)),
                ("html_url", models.URLField()),
                ("clone_url", models.URLField()),
                ("git_url", models.URLField()),
                ("stars_count", models.IntegerField(default=0)),
                ("forks_count", models.IntegerField(default=0)),
                ("watchers_count", models.IntegerField(default=0)),
                ("open_issues_count", models.IntegerField(default=0)),
                ("language", models.CharField(blank=True, max_length=100, null=True)),
                ("languages", models.JSONField(blank=True, default=dict)),
                ("topics", models.JSONField(blank=True, default=list)),
                ("is_private", models.BooleanField(default=False)),
                ("is_fork", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at_github", models.DateTimeField()),
                ("updated_at_github", models.DateTimeField()),
                ("pushed_at_github", models.DateTimeField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("custom_description", models.TextField(blank=True, null=True)),
                ("demo_url", models.URLField(blank=True, null=True)),
                ("last_synced", models.DateTimeField(auto_now=True)),
                (
                    "github_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories",
                        to="github_integration.githubprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-stars_count", "-updated_at_github"],
                "unique_together": {("github_profile", "name")},
            },
        ),
        migrations.CreateModel(
            name="Commit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sha", models.CharField(max_length=40, unique=True)),
                ("message", models.TextField()),
                ("date", models.DateTimeField()),
                ("additions", models.IntegerField(default=0)),
                ("deletions", models.IntegerField(default=0)),
                ("total_changes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "github_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="github_integration.githubprofile",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="github_integration.repository",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
