# Generated by Django 5.2.4 on 2026-01-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github_integration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubprofile",
            name="avatar_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="githubprofile",
            name="profile_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
