# Generated by Django 5.2.4 on 2026-01-22 05:36

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("github_integration", "0002_alter_githubprofile_avatar_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubprofile",
            name="access_token",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
