# Generated by Django 6.0.1 on 2026-01-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github_integration", "0003_alter_githubprofile_access_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="created_at_github",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="repository",
            name="updated_at_github",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
