# Generated by Django 6.0.1 on 2026-01-29 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_integration", "0004_alter_repository_created_at_github_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="commit",
            index=models.Index(fields=["sha"], name="github_inte_sha_ece264_idx"),
        ),
        migrations.AddIndex(
            model_name="commit",
            index=models.Index(
                fields=["repository", "date"], name="github_inte_reposit_678b52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="githubprofile",
            index=models.Index(
                fields=["github_username"], name="github_inte_github__ee556b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="githubsynclog",
            index=models.Index(
                fields=["github_profile", "sync_type", "status"],
                name="github_inte_github__6e8827_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["github_id"], name="github_inte_github__62e39c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["github_profile", "is_hidden"],
                name="github_inte_github__3eb284_idx",
            ),
        ),
    ]
