# Generated by Django 6.0.1 on 2026-02-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "github_integration",
            "0006_remove_repository_languages_alter_commit_additions_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="repository",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="commit",
            name="sha",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="repository",
            name="github_id",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="commit",
            unique_together={("repository", "sha")},
        ),
        migrations.AlterUniqueTogether(
            name="repository",
            unique_together={("github_profile", "github_id")},
        ),
    ]
