# Generated by Django 6.0.1 on 2026-02-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "github_integration",
            "0007_alter_repository_unique_together_alter_commit_sha_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commit",
            name="additions",
        ),
        migrations.RemoveField(
            model_name="commit",
            name="deletions",
        ),
        migrations.RemoveField(
            model_name="commit",
            name="total_changes",
        ),
        migrations.AddField(
            model_name="repository",
            name="weekly_stats",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
