# Generated by Django 6.0.1 on 2026-02-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "github_integration",
            "0008_remove_commit_additions_remove_commit_deletions_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="githubsynclog",
            name="stats_synced",
            field=models.IntegerField(default=0),
        ),
    ]
