# Generated by Django 6.0.1 on 2026-02-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_integration", "0009_githubsynclog_stats_synced"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="githubsynclog",
            name="stats_synced",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="weekly_stats",
        ),
        migrations.AlterField(
            model_name="githubsynclog",
            name="commits_synced",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="githubsynclog",
            name="repos_synced",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
