THEMES = [
    {
        "key": "minimal",
        "name": "Minimal",
        "description": "Clean, whitespace-heavy layout.",
        "config": {
            "primary_color": "#000000",
            "secondary_color": "#666666",
            "background_color": "#ffffff",
            "accent_color": "#eeeeee",
            "text_color": "#333333",
            "font_family": "Inter, sans-serif",
            "spacing": "md",
            "border_radius": 0,
            "dark_mode_enabled": False,
        },
    },
    {
        "key": "modern",
        "name": "Modern",
        "description": "Modern responsive card-based layout.",
        "config": {
            "primary_color": "#3b82f6",
            "secondary_color": "#1e40af",
            "background_color": "#f8fafc",
            "accent_color": "#60a5fa",
            "text_color": "#1e293b",
            "font_family": "Roboto, sans-serif",
            "spacing": "md",
            "border_radius": 8,
            "dark_mode_enabled": False,
        },
    },
    {
        "key": "classic",
        "name": "Classic",
        "description": "Resume-like structured portfolio layout.",
        "config": {
            "primary_color": "#2c3e50",
            "secondary_color": "#34495e",
            "background_color": "#ecf0f1",
            "accent_color": "#2980b9",
            "text_color": "#2c3e50",
            "font_family": "Georgia, serif",
            "spacing": "sm",
            "border_radius": 0,
            "dark_mode_enabled": False,
        },
    },
    {
        "key": "terminal",
        "name": "Terminal",
        "description": "Monospace CLI/terminal vibe.",
        "config": {
            "primary_color": "#00ff41",
            "secondary_color": "#008f11",
            "background_color": "#0d0208",
            "accent_color": "#003b00",
            "text_color": "#00ff41",
            "font_family": "Fira Code, monospace",
            "spacing": "lg",
            "border_radius": 0,
            "dark_mode_enabled": True,
        },
    },
    {
        "key": "glass",
        "name": "Glass",
        "description": "Glassmorphism + blur aesthetic.",
        "config": {
            "primary_color": "rgba(255, 255, 255, 0.4)",
            "secondary_color": "rgba(255, 255, 255, 0.2)",
            "background_color": "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
            "accent_color": "#ffffff",
            "text_color": "#ffffff",
            "font_family": "Poppins, sans-serif",
            "spacing": "lg",
            "border_radius": 16,
            "dark_mode_enabled": True,
        },
    },
    {
        "key": "professional",
        "name": "Professional",
        "description": "Corporate clean theme for recruiters.",
        "config": {
            "primary_color": "#2563eb",
            "secondary_color": "#1e40af",
            "background_color": "#ffffff",
            "accent_color": "#e2e8f0",
            "text_color": "#111827",
            "font_family": "Open Sans, sans-serif",
            "spacing": "md",
            "border_radius": 4,
            "dark_mode_enabled": False,
        },
    },
    {
        "key": "creative",
        "name": "Creative",
        "description": "Bold accents + visual design.",
        "config": {
            "primary_color": "#ff3366",
            "secondary_color": "#ff6b6b",
            "background_color": "#2d3436",
            "accent_color": "#00cec9",
            "text_color": "#dfe6e9",
            "font_family": "Montserrat, sans-serif",
            "spacing": "xl",
            "border_radius": 24,
            "dark_mode_enabled": True,
        },
    },
]

THEME_PRESETS = {theme["key"]: theme["config"] for theme in THEMES}
