# Generated by Django 5.2.4 on 2026-01-17 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("show_github_stats", models.BooleanField(default=True)),
                ("show_social_links", models.BooleanField(default=True)),
                ("show_forked_repos", models.BooleanField(default=False)),
                ("min_stars_to_show", models.IntegerField(default=0)),
                ("show_contributions", models.BooleanField(default=True)),
                ("show_recent_activity", models.BooleanField(default=True)),
                ("show_projects", models.BooleanField(default=True)),
                ("show_languages", models.BooleanField(default=True)),
                (
                    "layout_style",
                    models.CharField(
                        choices=[
                            ("grid", "Grid Layout"),
                            ("list", "List Layout"),
                            ("cards", "Card Layout"),
                            ("minimal", "Minimal Layout"),
                        ],
                        default="grid",
                        max_length=20,
                    ),
                ),
                ("projects_per_page", models.IntegerField(default=6)),
                ("enable_dark_mode", models.BooleanField(default=False)),
                ("allow_contact_form", models.BooleanField(default=True)),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "resume_file",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                ("meta_title", models.CharField(blank=True, max_length=60)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                (
                    "custom_domain",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_published", models.BooleanField(default=True)),
                (
                    "google_analytics_id",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio Settings",
                "verbose_name_plural": "Portfolio Settings",
            },
        ),
        migrations.CreateModel(
            name="SocialLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("github_url", models.URLField(blank=True, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                ("resume_url", models.URLField(blank=True, null=True)),
                ("dev_to_url", models.URLField(blank=True, null=True)),
                ("stackoverflow_url", models.URLField(blank=True, null=True)),
                ("hashnode_url", models.URLField(blank=True, null=True)),
                ("medium_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                ("youtube_url", models.URLField(blank=True, null=True)),
                (
                    "discord_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "telegram_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Links",
                "verbose_name_plural": "Social Links",
            },
        ),
        migrations.CreateModel(
            name="PortfolioSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("about", "About Me"),
                            ("skills", "Skills & Technologies"),
                            ("projects", "Projects"),
                            ("experience", "Experience"),
                            ("education", "Education"),
                            ("blog", "Blog Posts"),
                            ("testimonials", "Testimonials"),
                            ("contact", "Contact"),
                            ("custom", "Custom Section"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField(blank=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_sections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "unique_together": {("user", "section_type")},
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("programming", "Programming Languages"),
                            ("frontend", "Frontend Technologies"),
                            ("backend", "Backend Technologies"),
                            ("database", "Databases"),
                            ("devops", "DevOps & Tools"),
                            ("design", "Design Tools"),
                            ("other", "Other Skills"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "proficiency",
                    models.IntegerField(
                        default=50, help_text="Proficiency level (0-100)"
                    ),
                ),
                ("icon_url", models.URLField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-proficiency", "name"],
                "unique_together": {("user", "name")},
            },
        ),
    ]
