# Generated by Django 6.0.1 on 2026-01-29 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="portfoliosection",
            index=models.Index(fields=["user"], name="portfolios__user_id_bdf1a3_idx"),
        ),
        migrations.AddIndex(
            model_name="portfoliosettings",
            index=models.Index(fields=["slug"], name="portfolios__slug_6a3254_idx"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["user"], name="portfolios__user_id_90eaa9_idx"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["category"], name="portfolios__categor_819bdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sociallinks",
            index=models.Index(fields=["user"], name="portfolios__user_id_f4b9ee_idx"),
        ),
    ]
