# Generated by Django 6.0.1 on 2026-01-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolios", "0002_portfoliosection_portfolios__user_id_bdf1a3_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfoliosettings",
            name="min_stars_to_show",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
