# Generated by Django 6.0.1 on 2026-01-29 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0003_alter_portfoliosettings_min_stars_to_show"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfoliosettings",
            name="resume_file",
        ),
        migrations.AddField(
            model_name="portfoliosettings",
            name="resume_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="portfoliosection",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="portfoliosettings",
            name="custom_domain",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="portfoliosettings",
            name="min_stars_to_show",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="portfoliosettings",
            name="projects_per_page",
            field=models.PositiveIntegerField(
                default=6,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="proficiency",
            field=models.IntegerField(
                default=50,
                help_text="Proficiency level (0-100)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
