# Generated by Django 6.0.1 on 2026-01-30 05:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolios", "0004_remove_portfoliosettings_resume_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
    ]
